//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseSearchAdminTest.EncriptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.megatec.ru/", ConfigurationName="EncriptionService.EncryptionServiceSoap")]
    public interface EncryptionServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.megatec.ru/EncryptString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EncryptString(string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.megatec.ru/DecryptString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DecryptString(string source);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EncryptionServiceSoapChannel : CruiseSearchAdminTest.EncriptionService.EncryptionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EncryptionServiceSoapClient : System.ServiceModel.ClientBase<CruiseSearchAdminTest.EncriptionService.EncryptionServiceSoap>, CruiseSearchAdminTest.EncriptionService.EncryptionServiceSoap {
        
        public EncryptionServiceSoapClient() {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EncryptionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EncryptString(string source) {
            return base.Channel.EncryptString(source);
        }
        
        public string DecryptString(string source) {
            return base.Channel.DecryptString(source);
        }
    }
}
